### ISSUE TITLE
Does it work inside Docker? 

### ISSUE THREAD

**Issue by vchulski** [data-8/nbzip#18]
It's not working in my case. No any errors while installation: 
![nbzipinstallation](https://user-images.githubusercontent.com/31348740/47492962-d9f06e80-d856-11e8-9961-389acf6e3186.png)
![nbzipmistake](https://user-images.githubusercontent.com/31348740/47492964-d9f06e80-d856-11e8-8c9b-faf5ce13591e.png)

I am using Jupyter inside the Docker, could it influence?

**Comment by ryanlovett** [comment]
The server extension will be available after the server has been started. It won't be available immediately after you've installed it in a running server.

If you install the extension as part of your docker build then the extension will be available when you run the container. If you install the extension within your container on part of a file system that gets recreated when your container restarts, it won't be available.

**Comment by vchulski** [comment]
Thanks for your answer! 
It runs after server which hosts docker restart. 
Thanks a lot for this cool tool!
